remote_theme: pages-themes/minimal@v0.2.0
title: Shwetabh Biswas
description: Artificial Intelligence | Machine Learning | NLP | CV | Data Science | Life Long Learner
show_downloads: false
logo: /assests/img/my_photu.jpg